Initial signup component
chingu-voyages/v37-bears-team-13 pull request #38
Opened 2022-02-18 18:23 UTC by JessieFrance

This PR aims to create an initial sign up component for #12.

2022-02-18 18:48 UTC, ArturoDucasse requested changes
Overall it's pretty great, just requires minor changes that will just enhance a little bit the code.

Great job 😄

2022-02-18 18:48 UTC, ArturoDucasse commented on src/Signup.tsx
> +    // Do something with name, email, password, and confirmed password.
These console.logs will not be required in the production code

2022-02-18 18:48 UTC, ArturoDucasse commented on src/Signup.tsx
> +  const [name, setName] = useState("");
These inputs can be handled by one useState, [here](https://dev.to/deboragaleano/how-to-handle-multiple-inputs-in-react-55el) you can read more about it.

2022-02-18 18:48 UTC, ArturoDucasse commented on src/Signup.tsx
> +		  type="text"
Would be nice to have a [placeholder](https://www.w3schools.com/tags/att_input_placeholder.asp).

2022-02-18 18:48 UTC, ArturoDucasse commented on src/Signup.tsx
> +		  type="email"
Here as well

2022-02-18 19:00 UTC, rmcguire6 commented
I agree with Arthur's changes.

2022-02-18 20:54 UTC, JessieFrance commented
Thank you @ArturoDucasse and @rmcguire6 for the feedback on this. The changes have been made.

2022-02-18 22:01 UTC, rmcguire6 approved these changes
Looks great, Jessie.

2022-02-19 14:10 UTC, ArturoDucasse approved these changes
Nice, now is slightly better than it already was.

2022-02-19 14:11 UTC, merged