Updating main to our current dev release
chingu-voyages/v37-bears-team-13 pull request #52
Opened 2022-02-24 22:20 UTC by rmcguire6

2022-02-25 23:15 UTC, JessieFrance approved these changes
Aside from fixing some minor syntax in `.eslintrc.json`, I think this looks good to merge.

2022-02-25 23:15 UTC, JessieFrance commented on .eslintrc.json
> +  "plugins": ["react", "@typescript-eslint"]
There should be a comma after this line.

2022-02-25 23:15 UTC, JessieFrance commented on .eslintrc.json
> +  "react/jsx-key": [false, { "checkFragmentShorthand": true }]
I recommend deleting this line, adding a comma after line 18 in the rules block, and adding this modified version after line 18:
`"react/jsx-key": [0, { "checkFragmentShorthand": true }]`

2022-02-25 23:15 UTC, JessieFrance commented on .eslintrc.json
> +  "rules": { "react/react-in-jsx-scope": "off" }
This rule looks the same as line 18. I think it can be deleted.

2022-02-26 01:43 UTC, Rae-Kwon requested changes
Everything else looks perfect!!

2022-02-26 01:43 UTC, Rae-Kwon commented on .eslintrc.json
> +  "rules": {
There are two rules keys here and on line 21. Maybe remove line 21?

2022-02-26 01:43 UTC, Rae-Kwon commented on .eslintrc.json
> +  "plugins": ["react", "@typescript-eslint"]
Add comma after this line

2022-02-26 21:05 UTC, ArturoDucasse approved these changes

2022-02-27 16:46 UTC, Rae-Kwon approved these changes
Looks great!!!

2022-02-27 16:50 UTC, merged