fix: github pages deploy
chingu-voyages/v37-bears-team-13 pull request #68
Opened 2022-03-11 19:41 UTC by Rae-Kwon

This commit fixes the Github pages. There was a missing run in the predeploy script!! Should work now!!

 As this was a one word fix I have just gone from main to main!! I made sure it worked on my end!

2022-03-12 16:48 UTC, JessieFrance approved these changes
Looks good. Thank you Richard!

2022-03-14 15:47 UTC, ArturoGrullon requested changes

2022-03-14 15:47 UTC, ArturoDucasse commented on package.json
> +    "predeploy": "yarn run build",
The run command in Yarn is optional, for NPM is necessary: 
```bash
yarn build //works
yarn run build //works
npm run build //works
npm build //won't work 
```
[Here](https://stackoverflow.com/questions/40619269/what-is-the-difference-between-yarn-run-and-npm-start) you can read more about it, is one of the reasons I rather use yarn.

2022-03-14 15:47 UTC, ArturoDucasse commented on package.json
> +    "predeploy": "yarn run build",
That being said, I don't think this will fix the issue. Could be wrong though

2022-03-15 22:12 UTC, closed without merging